In [6]:
import pandas as pd
val_labels = pd.read_csv("data/val_labels.csv")

In [9]:
val_labels.head(43)

    wafer_id wafer_type fault_name fault_code_logged pass_fail_final
0       3301     normal       NONE              NONE            PASS
1       3302     normal       NONE              NONE            PASS
2       3303     normal       NONE              NONE            PASS
3       3304     normal       NONE              NONE            PASS
4       3305     normal       NONE              NONE            PASS
5       3306     normal       NONE              NONE            PASS
6       3307     normal       NONE              NONE            PASS
7       3308     normal       NONE              NONE            PASS
8       3309     normal       NONE              NONE            PASS
9       3310     normal       NONE              NONE            PASS
10      3311     normal       NONE              NONE            PASS
11      3312     normal       NONE              NONE            PASS
12      3313     normal       NONE              NONE            PASS
13      3314     normal       NONE              NONE            PASS
14      3315     normal       NONE              NONE            PASS
15      3316     normal       NONE              NONE            PASS
16      3317     normal       NONE              NONE            PASS
17      3321     normal       NONE              NONE            PASS
18      3322     normal       NONE              NONE            PASS
19      3323     normal       NONE              NONE            PASS
20      3324     normal       NONE              NONE            PASS
21      3325     normal       NONE              NONE            PASS
22      3326     normal       NONE              NONE            PASS
23      3327     normal       NONE              NONE            PASS
24      3328     normal       NONE              NONE            PASS
25      3329     normal       NONE              NONE            PASS
26      3330     normal       NONE              NONE            PASS
27      3331     normal       NONE              NONE            PASS
28      3332     normal       NONE              NONE            PASS
29      3333     normal       NONE              NONE            PASS
30      3334     normal       NONE              NONE            PASS
31      3335     normal       NONE              NONE            PASS
32      3336     normal       NONE              NONE            PASS
33      3337     normal       NONE              NONE            PASS
34      3338     normal       NONE              NONE            PASS
35      3342     normal       NONE              NONE            PASS
36      3343     normal       NONE              NONE            PASS
37      3318      fault    TCP -15           TCP -15            FAIL
38      3319      fault    Cl2 -10           Cl2 -10            FAIL
39      3320      fault     RF -12            RF -12            FAIL
40      3339      fault   BCl3 +10          BCl3 +10            FAIL
41      3340      fault      Pr +1             Pr +1            FAIL
42      3341      fault    TCP +20           TCP +20            FAIL

In [8]:
len(val_labels)

43

In [13]:
train_machine = pd.read_csv("data/train_machine.csv")
train_machine.head(43)

,wafer_id,experiment,step,time_sec,Step Number,BCl3 Flow,Cl2 Flow,RF Btm Pwr,RF Btm Rfl Pwr,Endpt A,...,RF Phase Err,RF Pwr,RF Impedance,TCP Tuner,TCP Phase Err,TCP Impedance,TCP Top Pwr,TCP Rfl Pwr,TCP Load,Vat Valve
0,2901,29,0,11.9460,4.0,751.0,753.0,132.0,0.0,626.0,...,-362.0,26.0,16599.0,20028.0,-296.0,16848.0,360.0,0.0,27594.0,49.0
1,2901,29,1,13.0280,4.0,751.0,753.0,134.0,0.0,620.0,...,-1455.0,26.0,16568.0,20042.0,-676.0,16796.0,350.0,0.0,27440.0,49.0
2,2901,29,2,14.0490,4.0,751.0,755.0,134.0,0.0,599.0,...,-1056.0,25.0,16442.0,20146.0,-291.0,16512.0,344.0,0.0,27276.0,49.0
3,2901,29,3,15.1329,4.0,751.0,753.0,133.0,0.0,586.0,...,-587.0,25.0,16960.0,20148.0,-262.0,17020.0,352.0,0.0,27330.0,50.0
4,2901,29,4,16.1390,4.0,751.0,754.0,132.0,0.0,587.0,...,-124.0,25.0,16564.0,20226.0,-547.0,16440.0,346.0,0.0,27262.0,50.0
5,2901,29,5,17.1589,4.0,751.0,753.0,134.0,0.0,1284.0,...,-417.0,25.0,16437.0,19478.0,1738.0,17366.0,350.0,1.0,28178.0,49.0
6,2901,29,6,18.2579,4.0,751.0,753.0,132.0,0.0,1627.0,...,-1661.0,26.0,16352.0,19544.0,-13.0,16130.0,346.0,1.0,27560.0,48.0
7,2901,29,7,19.3090,4.0,751.0,753.0,134.0,0.0,1624.0,...,-1189.0,25.0,16341.0,19590.0,452.0,16428.0,354.0,0.0,27974.0,48.0
8,2901,29,8,20.4200,4.0,751.0,753.0,135.0,1.0,1457.0,...,1343.0,24.0,16642.0,19416.0,-455.0,16964.0,356.0,0.0,27906.0,48.0
9,2901,29,9,21.4490,4.0,751.0,754.0,135.0,0.0,1338.0,...,-1016.0,25.0,16257.0,19614.0,1158.0,16350.0,354.0,0.0,27750.0,49.0
10,2901,29,10,22.4690,4.0,751.0,753.0,134.0,0.0,1503.0,...,-1807.0,25.0,16494.0,19452.0,1234.0,17038.0,343.0,0.0,27892.0,49.0
11,2901,29,11,23.5580,4.0,751.0,754.0,134.0,0.0,1519.0,...,-1027.0,25.0,16422.0,19438.0,136.0,16234.0,358.0,0.0,27890.0,48.0
12,2901,29,12,24.6489,4.0,751.0,753.0,133.0,0.0,1533.0,...,42.0,24.0,16623.0,19424.0,-278.0,16724.0,354.0,0.0,27838.0,49.0
13,2901,29,13,25.6689,4.0,751.0,753.0,139.0,0.0,1535.0,...,-1584.0,25.0,16730.0,19448.0,87.0,16852.0,346.0,0.0,27856.0,49.0
14,2901,29,14,26.6890,4.0,752.0,753.0,136.0,0.0,1545.0,...,-920.0,25.0,16535.0,19468.0,-307.0,16690.0,343.0,0.0,27856.0,49.0
15,2901,29,15,27.7150,4.0,751.0,753.0,133.0,0.0,1565.0,...,-356.0,25.0,16424.0,19464.0,-42.0,16708.0,349.0,1.0,27850.0,49.0
16,2901,29,16,28.7369,4.0,751.0,753.0,132.0,0.0,1580.0,...,-452.0,25.0,16484.0,19478.0,194.0,16566.0,348.0,0.0,27862.0,49.0
17,2901,29,17,29.8610,4.0,752.0,754.0,136.0,0.0,1592.0,...,-1423.0,24.0,16701.0,19454.0,89.0,15744.0,358.0,1.0,27858.0,49.0
18,2901,29,18,30.8340,4.0,752.0,753.0,135.0,0.0,1599.0,...,-931.0,24.0,16539.0,19360.0,692.0,16184.0,353.0,0.0,27866.0,49.0
19,2901,29,19,31.8530,4.0,752.0,753.0,141.0,0.0,1607.0,...,-1194.0,24.0,16532.0,19360.0,129.0,16856.0,351.0,0.0,27898.0,49.0
20,2901,29,20,32.8829,4.0,752.0,753.0,133.0,0.0,1602.0,...,-832.0,24.0,16781.0,19372.0,498.0,16474.0,353.0,1.0,27900.0,49.0
21,2901,29,21,33.9089,4.0,752.0,753.0,133.0,0.0,1611.0,...,-706.0,24.0,16564.0,19358.0,129.0,16764.0,357.0,0.0,27920.0,49.0
22,2901,29,22,34.9290,4.0,752.0,753.0,136.0,0.0,1611.0,...,-808.0,24.0,16474.0,19396.0,144.0,16858.0,349.0,1.0,27898.0,49.0
23,2901,29,23,35.9580,4.0,751.0,752.0,133.0,0.0,1606.0,...,-330.0,24.0,16164.0,19380.0,504.0,16182.0,345.0,1.0,27966.0,49.0
24,2901,29,24,36.9880,4.0,751.0,753.0,134.0,0.0,1610.0,...,-892.0,24.0,16253.0,19350.0,146.0,16536.0,348.0,0.0,27938.0,49.0
25,2901,29,25,38.0079,4.0,752.0,754.0,131.0,0.0,1602.0,...,-1270.0,23.0,16681.0,19372.0,86.0,16214.0,354.0,0.0,27930.0,49.0
26,2901,29,26,39.1090,4.0,752.0,753.0,132.0,0.0,1612.0,...,-1062.0,24.0,16430.0,19388.0,58.0,16768.0,358.0,0.0,27908.0,49.0
27,2901,29,27,40.1290,4.0,751.0,754.0,134.0,0.0,1608.0,...,-2202.0,24.0,16445.0,19382.0,-11.0,16394.0,347.0,0.0,27832.0,49.0
28,2901,29,28,41.1489,4.0,751.0,753.0,132.0,0.0,1611.0,...,-1077.0,24.0,16288.0,19354.0,-61.0,16298.0,354.0,0.0,28012.0,49.0
29,2901,29,29,42.1689,4.0,751.0,754.0,135.0,0.0,1612.0,...,-1294.0,24.0,16115.0,19344.0,118.0,16804.0,349.0,0.0,27914.0,49.0
30,2901,29,30,43.1890,4.0,751.0,754.0,134.0,0.0,1621.0,...,-1457.0,23.0,16574.0,19350.0,612.0,17028.0,347.0,0.0,27866.0,49.0
31,2901,29,31,44.2090,4.0,752.0,753.0,134.0,0.0,1619.0,...,-1023.0,24.0,16233.0,19368.0,-289.0,16558.0,348.0,0.0,27838.0,49.0
32,2901,29,32,45.2380,4.0,752.0,753.0,133.0,0.0,1613.0,...,-921.0,24.0,16381.0,19372.0,-64.0,16628.0,351.0,0.0,27778.0,49.0
33,2901,29,33,46.3359,4.0,752.0,752.0,136.0,0.0,1613.0,...,-1200.0,24.0,16567.0,19348.0,120.0,16460.0,349.0,0.0,27864.0,49.0
34,2901,29,34,47.3490,4.0,751.0,753.0,133.0,0.0,1614.0,...,-1331.0,24.0,16344.0,19332.0,-94.0,16690.0,360.0,0.0,27850.0,49.0
35,2901,29,35,48.3690,4.0,752.0,753.0,130.0,0.0,1616.0,...,-1850.0,24.0,16600.0,19358.0,5.0,16632.0,354.0,0.0,27908.0,49.0
36,2901,29,36,49.4509,4.0,751.0,753.0,133.0,0.0,1616.0,...,-183.0,24.0,16661.0,19360.0,-326.0,16972.0,345.0,1.0,27838.0,49.0
37,2901,29,37,50.4780,4.0,752.0,753.0,136.0,0.0,1619.0,...,-1261.0,24.0,16493.0,19328.0,30.0,15852.0,353.0,1.0,27880.0,49.0
38,2901,29,38,51.5890,4.0,752.0,754.0,133.0,0.0,1616.0,...,-1594.0,23.0,16236.0,19362.0,145.0,16412.0,343.0,0.0,28014.0,49.0
39,2901,29,39,52.6090,4.0,752.0,753.0,134.0,0.0,1618.0,...,-1297.0,24.0,16593.0,19334.0,-259.0,16842.0,347.0,0.0,27884.0,49.0
40,2901,29,40,53.7280,4.0,752.0,753.0,133.0,0.0,1620.0,...,-463.0,24.0,16344.0,19352.0,44.0,16874.0,348.0,0.0,27954.0,49.0
41,2901,29,41,54.8199,4.0,751.0,751.0,134.0,0.0,1618.0,...,-1443.0,24.0,16447.0,19352.0,72.0,16454.0,350.0,1.0,28012.0,49.0
42,2901,29,42,55.8440,4.0,752.0,754.0,134.0,0.0,1611.0,...,-1419.0,23.0,16584.0,19348.0,-439.0,16874.0,342.0,0.0,27890.0,49.0

In [11]:
len(train_machine)

8579

In [14]:
(train_machine['TCP Top Pwr'] > 360).sum()

np.int64(73)

In [18]:
train_machine[train_machine['wafer_id'] == 2918].head(100)

,wafer_id,experiment,step,time_sec,Step Number,BCl3 Flow,Cl2 Flow,RF Btm Pwr,RF Btm Rfl Pwr,Endpt A,...,RF Phase Err,RF Pwr,RF Impedance,TCP Tuner,TCP Phase Err,TCP Impedance,TCP Top Pwr,TCP Rfl Pwr,TCP Load,Vat Valve
3797,2918,29,0,10.7100,4.0,751.0,753.0,132.0,0.0,640.0,...,-1019.0,26.0,16490.0,19986.0,-410.0,16766.0,350.0000,0.0,27472.0,49.0
3798,2918,29,1,11.7300,4.0,751.0,753.0,135.0,0.0,627.0,...,-1412.0,26.0,16666.0,19990.0,-71.0,16790.0,353.0000,0.0,27614.0,49.0
3799,2918,29,2,12.7500,4.0,751.0,754.0,134.0,0.0,616.0,...,-1095.0,26.0,16652.0,20010.0,-578.0,16732.0,347.0000,0.0,27484.0,49.0
3800,2918,29,3,13.7896,4.0,751.0,755.0,136.0,0.0,550.0,...,-1473.0,28.0,15922.0,20250.0,-963.0,16260.0,347.0000,0.0,27332.0,47.0
3801,2918,29,4,14.7886,4.0,751.0,754.0,133.0,0.0,531.0,...,-615.0,27.0,16114.0,20422.0,-604.0,16032.0,356.0000,0.0,27290.0,46.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3885,2918,29,88,101.1210,5.0,751.0,754.0,134.0,0.0,993.0,...,783.0,21.0,16853.0,19310.0,-480.0,16356.0,345.0000,0.0,28304.0,46.0
3886,2918,29,89,102.1400,5.0,752.0,753.0,134.0,0.0,992.0,...,902.0,21.0,16719.0,19100.0,-53.0,16428.0,345.0000,0.0,28098.0,46.0
3887,2918,29,90,103.1600,5.0,752.0,754.0,136.0,0.0,996.0,...,792.0,21.0,16938.0,19222.0,-288.0,16424.0,343.0000,0.0,28262.0,46.0
3888,2918,29,91,104.1800,5.0,752.0,753.0,132.0,0.0,990.0,...,929.0,21.0,16534.0,19160.0,-280.0,16438.0,359.0000,1.0,28290.0,46.0
3889,2918,29,92,9.7188,4.0,751.0,754.0,133.0,0.0,664.0,...,-1455.0,26.0,16676.0,19862.0,33.0,16798.0,346.6721,0.0,27644.0,49.0

In [19]:
# change columns in data frame to snake_case format
def to_snake_case(name):
    return name.strip().lower().replace(' ', '_')

def snake_case_columns(df):
    df.columns = [to_snake_case(c) for c in df.columns]
    return df

data = snake_case_columns(train_machine)

In [20]:
train_machine.head()

,wafer_id,experiment,step,time_sec,step_number,bcl3_flow,cl2_flow,rf_btm_pwr,rf_btm_rfl_pwr,endpt_a,...,rf_phase_err,rf_pwr,rf_impedance,tcp_tuner,tcp_phase_err,tcp_impedance,tcp_top_pwr,tcp_rfl_pwr,tcp_load,vat_valve
0,2901,29,0,11.9460,4.0,751.0,753.0,132.0,0.0,626.0,...,-362.0,26.0,16599.0,20028.0,-296.0,16848.0,360.0,0.0,27594.0,49.0
1,2901,29,1,13.0280,4.0,751.0,753.0,134.0,0.0,620.0,...,-1455.0,26.0,16568.0,20042.0,-676.0,16796.0,350.0,0.0,27440.0,49.0
2,2901,29,2,14.0490,4.0,751.0,755.0,134.0,0.0,599.0,...,-1056.0,25.0,16442.0,20146.0,-291.0,16512.0,344.0,0.0,27276.0,49.0
3,2901,29,3,15.1329,4.0,751.0,753.0,133.0,0.0,586.0,...,-587.0,25.0,16960.0,20148.0,-262.0,17020.0,352.0,0.0,27330.0,50.0
4,2901,29,4,16.1390,4.0,751.0,754.0,132.0,0.0,587.0,...,-124.0,25.0,16564.0,20226.0,-547.0,16440.0,346.0,0.0,27262.0,50.0

In [29]:
# filter for wafer 2918, first 8 steps, pressure column only
wafer_2918 = train_machine[
    (train_machine['wafer_id'] == 2918) &
    (train_machine['step'] < 8)
][['wafer_id', 'step', 'pressure']]

wafer_2918

      wafer_id  step   pressure
3797      2918     0   943.0518
3798      2918     1   943.0518
3799      2918     2   942.0518
3800      2918     3  1042.0518
3801      2918     4  1117.0518
3802      2918     5  1172.0518
3803      2918     6  1196.0518
3804      2918     7  1215.0518

In [30]:
import numpy as np
values = np.array([943.0518, 943.0518, 942.0518, 1042.0518, 1117.0518, 1172.0518, 1196.0518, 1215.0518])

In [32]:
x = np.arange(len(values))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [33]:
# fit a straight line through the points
slope, intercept = np.polyfit(x, values, 1)
print(f"Slope     : {slope:.4f}")
print(f"Intercept : {intercept:.4f}")

# predicted values on the fitted line
y_pred = slope * x + intercept
print(f"Predicted : {y_pred.round(2)}")

# SS_residual — how far actual values deviate from the line
ss_res = np.sum((values - y_pred) ** 2)
print(f"SS_residual: {ss_res:.4f}")

# SS_total — total variation in the data around the mean
ss_tot = np.sum((values - values.mean()) ** 2)
print(f"SS_total   : {ss_tot:.4f}")

# R-squared
r_squared = 1 - (ss_res / ss_tot)
print(f"R²         : {r_squared:.4f}")

Slope     : 46.8333
Intercept : 907.3851
Predicted : [ 907.39  954.22 1001.05 1047.89 1094.72 1141.55 1188.39 1235.22]
SS_residual: 6806.3333
SS_total   : 98927.5000
R²         : 0.9312

In [34]:
# filter for wafer 2918, first 8 steps, pressure column only
wafer_3142 = train_machine[
    (train_machine['wafer_id'] == 3142) &
    (train_machine['step'] < 8)
][['wafer_id', 'step', 'pressure']]

wafer_3142

      wafer_id  step   pressure
8387      3142     0  1074.4678
8388      3142     1  1072.4678
8389      3142     2  1072.4678
8390      3142     3  1118.4678
8391      3142     4  1135.4678
8392      3142     5  1176.4678
8393      3142     6  1212.4678
8394      3142     7  1227.4678

In [35]:
values_2 = np.array([1074.4678, 1072.4678, 1072.4678, 1118.4678, 1135.4678, 1176.4678, 1212.4678, 1227.4678])

In [36]:
x_2 = np.arange(len(values))
x_2

array([0, 1, 2, 3, 4, 5, 6, 7])

In [37]:
# fit a straight line through the points
slope_2, intercept_2 = np.polyfit(x_2, values_2, 1)
print(f"Slope     : {slope_2:.4f}")
print(f"Intercept : {intercept_2:.4f}")

# predicted values on the fitted line
y_pred_2 = slope_2 * x_2 + intercept_2
print(f"Predicted : {y_pred.round(2)}")

# SS_residual — how far actual values deviate from the line
ss_res_2 = np.sum((values_2 - y_pred_2) ** 2)
print(f"SS_residual: {ss_res_2:.4f}")

# SS_total — total variation in the data around the mean
ss_tot_2 = np.sum((values_2 - values_2.mean()) ** 2)
print(f"SS_total   : {ss_tot_2:.4f}")

# R-squared
r_squared_2 = 1 - (ss_res_2 / ss_tot_2)
print(f"R²         : {r_squared_2:.4f}")

Slope     : 25.0000
Intercept : 1048.7178
Predicted : [ 907.39  954.22 1001.05 1047.89 1094.72 1141.55 1188.39 1235.22]
SS_residual: 1767.5000
SS_total   : 28017.5000
R²         : 0.9369

## Manual Test - Quality Agent